_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.10.12
            "5": 0.18.5
            "8":
                - 1
                - 5
            "12": 0.18.5
            "13": linux-x86_64
BATCH_SIZE:
    value: 32
EPSILON_DECAY:
    value: 0.995
GAMMA:
    value: 0.99
LR:
    value: 0.0001
MEMORY_SIZE:
    value: 10000
