_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
                - 61
            "4": 3.12.3
            "5": 0.18.7
            "8":
                - 1
                - 3
                - 5
            "12": 0.18.7
            "13": windows-amd64
GAMMA:
    value: 0.99
HIDDEN_SIZE:
    value: 128
HORIZON:
    value: 500
LEARNING_RATE:
    value: 0.001
MAX_TRAJECTORIES:
    value: 10000
REINFORCE:
    value: true
